PRIVATE_BATHROOM_KEYWORDS: list[str] = [
    "private bath",
    "private bathroom",
    "own bath",
    "own bathroom",
    "en suite",
    "ensuite",
    "en-suite",
    "private restroom",
    "attached bathroom",
    "bathroom in the room",
    "dedicated bathroom",
]

BOROUGH_NEIGHBORHOODS: dict[str, dict[str, list[str]]] = {
    "Brooklyn": {
        "Bay Ridge":                     ["bay ridge", "bayridge"],
        "Bed-Stuy":                      ["bed-stuy", "bedstuy", "bed stuy"],
        "Bensonhurst":                   ["bensonhurst"],
        "Boerum Hill":                   ["boerum hill"],
        "Brighton Beach":                ["brighton beach"],
        "Brooklyn Heights":              ["brooklyn heights"],
        "Bushwick":                      ["bushwick"],
        "Canarsie":                      ["canarsie"],
        "Carroll Gardens":               ["carroll gardens"],
        "Clinton Hill":                  ["clinton hill"],
        "Cobble Hill":                   ["cobble hill"],
        "Coney Island":                  ["coney island"],
        "Crown Heights":                 ["crown heights"],
        "Ditmas Park":                   ["ditmas park"],
        "Downtown Brooklyn":             ["downtown brooklyn"],
        "DUMBO":                         ["dumbo"],
        "Dyker Heights":                 ["dyker heights"],
        "East Flatbush":                 ["east flatbush"],
        "Flatbush":                      ["flatbush"],
        "Flatlands":                     ["flatlands"],
        "Fort Greene":                   ["fort greene", "fort green"],
        "Gowanus":                       ["gowanus"],
        "Greenpoint":                    ["greenpoint"],
        "Kensington":                    ["kensington"],
        "Midwood":                       ["midwood"],
        "Park Slope":                    ["park slope"],
        "Prospect Heights":              ["prospect heights"],
        "Prospect Lefferts Gardens":     [
            "prospect lefferts gardens",
            "prospect lefferts garden",
            "plg"
        ],
        "Red Hook":                      ["red hook", "redhook", "red-hook"],
        "Sheepshead Bay":                ["sheepshead bay"],
        "Sunset Park":                   ["sunset park"],
        "Williamsburg":                  ["williamsburg"],
        "Windsor Terrace":               ["windsor terrace"],
    },
    "Manhattan": {
        "Alphabet City":      ["alphabet city"],
        "Battery Park City":  ["battery park city", "bpc"],
        "Chelsea":            ["chelsea"],
        "Chinatown":          ["chinatown"],
        "Civic Center":       ["civic center"],
        "East Harlem":        ["east harlem"],
        "East Village":       ["east village", "ev"],
        "Financial District": ["financial district", "fidi"],
        "Flatiron":           ["flatiron"],
        "Gramercy":           ["gramercy"],
        "Hamilton Heights":   ["hamilton heights"],
        "Harlem":             ["harlem"],
        "Hell's Kitchen":     ["hell's kitchen", "hells kitchen"],
        "Hudson Yards":       ["hudson yards"],
        "Inwood":             ["inwood"],
        "Kips Bay":           ["kips bay"],
        "Lincoln Square":     ["lincoln square"],
        "Little Italy":       ["little italy"],
        "Lower East Side":    ["lower east side", "les"],
        "Manhattan Valley":   ["manhattan valley"],
        "Manhattanville":     ["manhattanville"],
        "Midtown":            ["midtown"],
        "Morningside Heights":["morningside heights"],
        "Murray Hill":        ["murray hill"],
        "NoHo":               ["noho"],
        "Nolita":             ["nolita"],
        "NoMad":              ["nomad"],
        "Roosevelt Island":   ["roosevelt island"],
        "SoHo":               ["soho"],
        "Stuyvesant Town":    ["stuyvesant town", "stuy town", "stuytown"],
        "Sugar Hill":         ["sugar hill"],
        "Sutton Place":       ["sutton place"],
        "Tribeca":            ["tribeca"],
        "Turtle Bay":         ["turtle bay"],
        "Two Bridges":        ["two bridges"],
        "Upper East Side":    ["upper east side", "ues"],
        "Upper West Side":    ["upper west side", "uws"],
        "Washington Heights": ["washington heights"],
        "West Village":       ["west village", "wv"],
        "Yorkville":          ["yorkville"],
    },
    "Queens": {
        "Astoria":          ["astoria"],
        "Bayside":          ["bayside"],
        "College Point":    ["college point"],
        "Corona":           ["corona"],
        "Elmhurst":         ["elmhurst"],
        "Flushing":         ["flushing"],
        "Forest Hills":     ["forest hills"],
        "Fresh Meadows":    ["fresh meadows"],
        "Jackson Heights":  ["jackson heights"],
        "Jamaica":          ["jamaica"],
        "Kew Gardens":      ["kew gardens"],
        "Long Island City": ["long island city", "lic"],
        "Maspeth":          ["maspeth"],
        "Middle Village":   ["middle village"],
        "Rego Park":        ["rego park"],
        "Ridgewood":        ["ridgewood"],
        "Rockaway":         ["rockaway"],
        "Sunnyside":        ["sunnyside"],
        "Whitestone":       ["whitestone"],
        "Woodside":         ["woodside"],
    },
    "Bronx": {
        "Belmont":             ["belmont"],
        "Concourse":           ["concourse", "grand concourse"],
        "Fordham":             ["fordham"],
        "Kingsbridge":         ["kingsbridge"],
        "Morris Park":         ["morris park"],
        "Mott Haven":          ["mott haven"],
        "Parkchester":         ["parkchester"],
        "Pelham Bay":          ["pelham bay"],
        "Riverdale":           ["riverdale"],
        "South Bronx":         ["south bronx"],
        "Throgs Neck":         ["throgs neck", "throggs neck"],
        "University Heights": ["university heights"],
        "Woodlawn":            ["woodlawn"],
    },
    "Staten Island": {
        "Great Kills": ["great kills"],
        "New Dorp":    ["new dorp"],
        "Port Richmond": ["port richmond"],
        "St. George":  ["st. george", "st george", "saint george"],
        "Stapleton":   ["stapleton"],
        "Tottenville": ["tottenville"],
        "West Brighton": ["west brighton"],
    },
}

# Derived from BOROUGH_NEIGHBORHOODS — each entry adds borough-level catch-alls
# so posts that mention only "Brooklyn" still match when no specific neighborhoods are selected.
BOROUGH_KEYWORDS: dict[str, list[str]] = {
    "Brooklyn":     ["brooklyn", "bk", "bklyn"] + [kw for kws in BOROUGH_NEIGHBORHOODS["Brooklyn"].values() for kw in kws],
    "Manhattan":    ["manhattan"]                  + [kw for kws in BOROUGH_NEIGHBORHOODS["Manhattan"].values() for kw in kws],
    "Queens":       ["queens"]                     + [kw for kws in BOROUGH_NEIGHBORHOODS["Queens"].values() for kw in kws],
    "Bronx":        ["bronx"]                      + [kw for kws in BOROUGH_NEIGHBORHOODS["Bronx"].values() for kw in kws],
    "Staten Island":["staten island"]              + [kw for kws in BOROUGH_NEIGHBORHOODS["Staten Island"].values() for kw in kws],
}

# Posts are excluded if they contain ANY of these terms (case-insensitive).
EXCLUDE_KEYWORDS: list[str] = [
    "short term sublet",
    "short-term sublet",
    "summer sublet",
    "/day",
    "no option to renew",
    "no option to take over",
    "no option to takeover",
    "no option to extend",
    "not an option to renew",
    "cannot be renewed",
    "cannot renew",
    "can't renew",
    "no renewal option",
    "no lease takeover",
    "no lease renewal",
]

# How many posts to scrape per group per run
MAX_POSTS_PER_GROUP: int = 200

# Cutoff time for posts to collect
SECONDS_24H: int = 86_400

# Browser session storage path (keeps you logged in between runs)
SESSION_PATH: str = "session"
